version: "3.7"
services:
  db:
    image: mysql
    container_name: cnu-order
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cnu123
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - D:/mysql/data:/var/lib/mysql